name: SE project actions

on:
  push:
    branches: [ task-2 ]
  pull_request:
    branches: [ master ]

jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup
        run: |
          python3 -m pip install fastapi[all]
          python3 -m pip install -r requirements.txt

      - name: PyLint
        if: always()
        run: python3 -m pylint hse-SE-course tests

      - name: Mypy
        if: always()
        run: python3 -m mypy tests

      - name: Flake8
        if: always()
        run: python3 -m flake8 tests

      - name: Coverage 85%
        if: always()
        run: |
          coverage run -m pytest tests/unit_tests.py
          coverage report --fail-under 85
