name: SE project actions

on:
  push:
    branches: [ task-2, task-3 ]
  pull_request:
    branches: [ master ]

jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup
        run: /bin/bash setup.sh python3
#        run: |
#          python3 -m pip install fastapi[all]
#          python3 -m pip install -r requirements.txt

      - name: PyLint
        if: always()
        run: /bin/bash actions.sh pylint

      - name: Mypy
        if: always()
        run: /bin/bash actions.sh mypy

      - name: Flake8
        if: always()
        run: /bin/bash actions.sh flake8

      - name: Coverage 85%
        if: always()
        run: /bin/bash actions.sh coverage
