name: SE project actions

on:
  push:
    branches: [ task-2, task-3 ]
  pull_request:
    branches: [ master ]

jobs:
  TestingAndLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Setup
        run: /bin/bash setup.sh python3

      - name: PyLint
        run: /bin/bash actions.sh pylint

      - name: Mypy
        run: /bin/bash actions.sh mypy

      - name: Flake8
        run: /bin/bash actions.sh flake8

      - name: Coverage 90%
        run: /bin/bash actions.sh coverage
